# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Dev environment
variables:
  # Global
  ap_vm_image: ubuntu-20.04

  namespace: mlopsdemo #Note: A namespace with many characters will cause storage account creation to fail due to storage account names having a limit of 24 characters.
  postfix: 0001
  location: westus2
  environment: dev
  enable_aml_computecluster: true
  enable_monitoring: true

  # Azure DevOps
  ado_service_connection_rg: Azure-ARM-Dev
  ado_service_connection_aml_ws: Azure-ARM-Dev

  # DO NOT TOUCH

  # For pipeline reference
  resource_group: tap-test-rg
  aml_workspace: tap-aml-test
  application_insights: tapamltest9506171366
  key_vault: tapamltest3154612860
  container_registry: tapcrtest
  storage_account: tapamltest8407276530

  # For terraform reference
  terraform_version: 1.3.6
  terraform_workingdir: infrastructure
  terraform_st_location: $(location)
  terraform_st_resource_group: rg-$(namespace)-$(postfix)$(environment)-tf
  terraform_st_storage_account: st$(namespace)$(postfix)$(environment)tf
  terraform_st_container_name: default
  terraform_st_key: mlops-tab
